# Generated by Django 5.2.15 on 2026-06-17 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='extra_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
