# Generated by Django 5.2.15 on 2026-06-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Checked_in', 'Checked_in'), ('Checked_out', 'Checked_out'), ('Cancelled', 'Cancelled'), ('Rejected', 'Rejected')], default='Booked', max_length=50),
        ),
    ]
