# Generated by Django 5.2.15 on 2026-06-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_booking_extra_charges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Checked_in', 'Checked_in'), ('Checked_out', 'Checked_out'), ('dirty', 'dirty')], default='Booked', max_length=50),
        ),
    ]
