# Generated by Django 5.2.15 on 2026-06-15 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_room_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='check_in_time',
            field=models.CharField(default='12:00 PM', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='check_out_time',
            field=models.CharField(default='12:00 PM', max_length=10),
        ),
    ]
