# Generated by Django 5.2.15 on 2026-06-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_booking_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='extra_charges_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
