# Generated by Django 5.2.15 on 2026-06-15 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_booking_check_in_time_booking_check_out_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='advance_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Paid', max_length=20),
        ),
    ]
