# Generated by Django 5.2.15 on 2026-06-15 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_booking_advance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Hold', 'Hold'), ('Temp Reserve', 'Temp Reserve'), ('Reserve', 'Reserve'), ('Checked-In', 'Checked-In'), ('Checked-Out', 'Checked-Out')], default='Reserve', max_length=50),
        ),
    ]
