# Generated by Django 5.2.15 on 2026-06-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='cleanliness',
            field=models.CharField(choices=[('clean', 'Clean'), ('dirty', 'Dirty')], default='clean', max_length=20),
        ),
    ]
