# Generated by Django 5.2.15 on 2026-06-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_room_cleanliness'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='checked_out',
            field=models.BooleanField(default=False),
        ),
    ]
