# Generated by Django 5.2.15 on 2026-06-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Hold', 'Hold'), ('Temp Reserve', 'Temp Reserve'), ('Booked', 'Booked'), ('Checked-In', 'Checked-In'), ('Checked-Out', 'Checked-Out')], default='Booked', max_length=50),
        ),
    ]
